### PR TITLE
Add peak detection and marching cubes

### LINKED ISSUE #3: Peak detection and marching cubes?
Hi @guiwitz ,

Would you be interested in having the `peak_local_max` as well as the `marching_cubes` algorithms within this project? I don't think I've seen it implemented often elsewhere and I think they are quite useful to transition more easily between `image` layers > `points` layer as  well as `Labels` layers > `Surface` layers.

From a menu perspective, I would put them into the following places:

```
Layers
  - Layer Type
    - Detect local maxima (returns points layer)
    - Marching cubes (returns surface layer)
```

With the structure you have already provided I don't think it should be a lot of effort to implement - let me know what you think :)

### PR DESCRIPTION
**Pull request by jo-mueller**
Fixes #3

Implement `peak_local_max` and `marching_cubes` algorithms in the project.

* Add `peak_local_max_widget` function in `src/napari_skimage/skimage_detection_widget.py` to detect local maxima in image layers and return points layer.
* Add `marching_cubes_widget` function in `src/napari_skimage/skimage_detection_widget.py` to apply marching cubes algorithm on labels layers and return surface layer.
* Update `src/napari_skimage/napari.yaml` to include commands and widgets for `peak_local_max_widget` and `marching_cubes_widget`.
* Update `src/napari_skimage/__init__.py` to import `peak_local_max_widget` and `marching_cubes_widget`.
* Add tests for `peak_local_max_widget` and `marching_cubes_widget` in `src/napari_skimage/_tests/test_detection_widgets.py`.

## Tests

- [x] Tested interactively
- [x] Tested manually from viewer

### CODE REVIEW

**Comment by guiwitz** [comment]
Hi @jo-mueller, thanks for the PR! A few comments, first on peak local maxima:
- the maximum possible threshold is 999, which e.g. won't work for 16 bit images. We can either set this to 65535 or adjust it to the current max of the image. The latter solution requires making a more complex widget (like I did [here](https://github.com/guiwitz/napari-skimage/blob/899828151ead9a9c36fdafb3c6ca7d96ea978256/src/napari_skimage/skimage_threshold_widget.py#L51) for the threshold) but probably the first solution is sufficient at this point as most people don't have floating points values larger than the uint16 max value.
- To be consistent it would be great to have the link to the skimage function in the widget. For that you need to add an ```_on_init``` function as done e.g. [here](https://github.com/guiwitz/napari-skimage/blob/899828151ead9a9c36fdafb3c6ca7d96ea978256/src/napari_skimage/skimage_restoration_widget.py#L22) and use it in your widget function as done [here](https://github.com/guiwitz/napari-skimage/blob/899828151ead9a9c36fdafb3c6ca7d96ea978256/src/napari_skimage/skimage_restoration_widget.py#L35). You should be able to re-use almost exactly the function mentioned above, just fixing the function name recovery with ```func_name = '_'.join(widget.label.split(' ')[0:-1])```
- Maybe we should add the options ```exclude_border``` and ```num_peaks``` as they are simple to implement?

For the marching cube: 
- currently the widget is sort of a "sub-case" for label layers. However the skimage function is more generic and can accept a regular image with a ```level``` to use as threshold. I think users would be confused not being able to use the function for that case. As it is definitely useful (e.g. to select a specific label), I could imagine to keep the current function under a name like "Labels Marching Cube" and still have a widget for the generic implementation. That one would have a ```level``` slider.
- In both cases it might be good to use the ```spacing``` option. Maybe we can just re-use the scaling information from napari instead of asking again for those values.

Let me know what you think!

**Comment by jo-mueller** [comment]
Hi @guiwitz, 

thanks for the comprehensive feedback which I finally got around to implement. Maybe two notes:

> For that you need to add an _on_init function 

I added that, but I had to tailor the functions a bit to the respective widget as they both come from different skimage modules - hope that's fine :)

> Maybe we should add the options exclude_border and num_peaks as they are simple to implement?

The `exclude border` I added but the `num_peaks` I left out, as it defaults to `np.inf` in the skimage API. And I find optional arguments still a bit tricky to handle in magicgui :/

**Comment by jo-mueller** [comment]
Thanks for the fix!

**Comment by guiwitz** [comment]
Thanks for the contribution @jo-mueller !

**Pull request merged**
